### ISSUE TITLE
CMake does not generate includes 

### ISSUE THREAD

**Issue by bagrorg** [kurapov-peter/dwarf_bench#48]
I run dwarfs inside `docker` built from `Dockerfile` in repo.
I am building project as follows:
```console
CXX=dpcpp cmake /dwarf_bench/ -DENABLE_DPCPP=on
make -j 4
cmake --install /dwarf_bench/build --prefix /dwarf_bench/install
```
Then `/dwarf_bench/install` has only `bin` and `lib` files

**Comment by kurapov-peter** [comment]
The installation should contain the driver's headers only, let's add the `bench.hpp`
